apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tank
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: 'tank环境'
  destinations:
  - name: in-cluster
    namespace: '*'
    server: https://kubernetes.default.svc
   #server: https://192.168.0.80:14143
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'
  sourceNamespaces:
  - '*'
